import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
	src: [
		{
			path: "./fonts/Inter_18pt-Regular.ttf",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/Inter_18pt-SemiBold.ttf",
			weight: "600",
			style: "normal",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased bg-background-secondary`}>{children}</body>
		</html>
	);
}
